# Generated by Django 4.2.5 on 2023-11-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productimages_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='ProductName',
        ),
    ]
